### ISSUE TITLE
Remove eval

### ISSUE THREAD

**Issue by DuBistKomisch** [indutny/asn1.js#108]
`vm.runInThisContext` is essentially eval, and via browserify it is exactly eval

This was wrapped in a try-catch at least with #37, but the try still triggers a CSP violation/report.

Modern JS engines can infer the name from context, not just the define-time name, and with ES6 you can even do this properly without eval. Maybe we can get rid of this now?

https://stackoverflow.com/a/48899028
https://stackoverflow.com/a/9479081

**Comment by noppa** [comment]
This is also a adding lots of unneeded code for many people who use Webpack, because Webpack tries to automatically polyfill Node's Script module with a eval/iframe-based solution. Ironically, Webpack actually includes this library as an indirect dependency when someone tries to use the global `crypto` object and Webpack needs to polyfill that, too. This can be prevented manually with the right settings in Webpack config, but lots of people probably don't know about / aren't doing that.

**Comment by indutny** [comment]
Sorry, it should be fixed now!

**Comment by DuBistKomisch** [comment]
awesome thanks, now just need to wait a few years for it to flow up the transient dependencies :man_facepalming:

**Comment by noppa** [comment]
Thanks @indutny.  

@DuBistKomisch if you happen to be using yarn instead of npm, you can use its [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) option to force latest version of this. 
```json
package.json

"resolutions": {
    "webpack/**/asn1.js": "5.1.0"
}
```
did the trick for me. This might potentially break stuff, though, if there are breaking changes between the required version and the new one.

**Comment by ChALkeR** [comment]
`parse-asn1` is still using `asn1.js@4.10.1`, which has `named = require('vm').runInThisContext(`.

Could perhaps `parse-asn1` be bumped to use asn1.js@5, or this change go into asn1.js@4?

`parse-asn1` looks [highly popular](https://www.npmjs.com/package/parse-asn1).

**Comment by DuBistKomisch** [comment]
btw, I ended up using yarn resolutions as well and it seems to be working, can't really track down why the major version got bumped anyway

**Comment by cnemo-cenic** [comment]
Note that the version of asn1.js including this fix was pulled in by browserify/parse-asn1 back in 2020, however a year ago the maintainer of that package decided to downgrade their asn1.js dependency back to version 4 [1], I guess to maintain compatibility with older browsers and other older environments. So if you upgrade from parse-asn1 5.1.6 to 5.1.7, you lose the fix for this issue.[2]

I currently have the following override in my package.json:

```
"parse-asn1": {
  "asn1.js": "^5.4.1"
}
```

I guess someone could backport the fix for this issue to asn1.js v4, but perhaps there are other fixes in asn1.js v5 that you'd miss out on.

[1] https://github.com/browserify/parse-asn1/commit/f23087045497c93bd0a151e29b1e3f738e898cb8

[2] https://github.com/browserify/parse-asn1/issues/47
