### ISSUE TITLE
Doesn't work in Chrome Apps

### ISSUE THREAD

**Issue by Alex7Kom** [indutny/asn1.js#37]
`vm-browserify` uses `eval` which is disabled in Chrome Apps (completely) and Extensions (by default CSP), therefore browserified `asn1.js` doesn't work.
https://developer.chrome.com/extensions/sandboxingEval
https://developer.chrome.com/apps/contentSecurityPolicy

**Comment by indutny** [comment]
Right! Good that you found it!

I think the problem is with the following code:

https://github.com/indutny/asn1.js/blob/master/lib/asn1/api.js#L20-L22

It doesn't have any other use than the better error stack traces. Guess, it could be polyfill'ed for the browser by just using proper function.

I wonder if you might be interested in helping me with this! I would really appreciate it!

**Comment by Alex7Kom** [comment]
I'm sorry, I don't understand.
I tried to find a way to do this without `eval`/`new Function` but it seems there is no such way. Or did you mean to just replace it with an anonymous function?

**Comment by indutny** [comment]
@Alex7Kom thanks for taking a look! I meant replacing it with anonymous function, sorry for the confusion!

**Comment by Alex7Kom** [comment]
I thought that without that named function the method doesn't seem to make any sense, so I removed it.
https://github.com/indutny/asn1.js/pull/38
